#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/database
- name: Run PostgreSQL
  community.docker.docker_container:
    name: postgres
    image: kaisluce/tp-devops-database
    restart_policy: always
    env:
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    networks:
      - name: app-network
    volumes:
      - db_data:/var/lib/postgresql/data
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python
