#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/network
- name: Create Docker network
  community.docker.docker_network:
    name: app-network
    state: present
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python

- name: Create Docker network
  community.docker.docker_network:
    name: proxy-network
    state: present
  vars:
    ansible_python_interpreter: /opt/docker_venv/bin/python
