name: Continuous Deployment

on:
  workflow_run:
    workflows: ["CI devops 2025"]
    types: [completed]

concurrency:
  group: deploy-prod
  cancel-in-progress: false

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible-core~=2.17 community.docker~=4.6

      - name: Prepare SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H kais.luce-laurent.takima.cloud >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy with Ansible
        working-directory: ansible
        env:
          ANSIBLE_FORCE_COLOR: "true"
        run: ansible-playbook -i inventories/setup.yml playbook.yml --private-key ~/.ssh/id_rsa
